### ISSUE TITLE
Format email message.

### ISSUE THREAD

**Issue by sroutier** [tylercd100/lern#33]
Hello,

Thanks for this great package.

Do you know of a good way to format the email message that is sent?
In the "Changing the text" section of your README, you show us how to do some formatting and how to add details but the HTML formatting is not retained.
Ideally LERN would make use and publish templates that could be customized.

Any thoughts?

Cheers.
/S

**Comment by tylercd100** [comment]
Hey Sebastian, thanks for reaching out. I like the idea of using templates
for LERN. Let me get back to you after I've done some digging through the
code.

**Comment by tylercd100** [comment]
Hey @sroutier I just saw the [package](https://github.com/sroutier/laravel-5.1-enterprise-starter-kit) you are working on. What an honor! :)

I'll try an make sure I get this done this week

**Comment by sroutier** [comment]
Thanks, would be great if email templates could be supported. It would add some polish and customizations.
Could not have done it without the great packages created and open-sourced by the community like yourself.

Cheers.
/S

**Comment by eleftrik** [comment]
I agree with @sroutier, using an e-mail template would be great.

**Comment by tylercd100** [comment]
Hey @sroutier and @eleftrik. I have released version [3.6.5](https://github.com/tylercd100/lern/releases/tag/3.6.5) which allows for html in emails. 

I am still going to keep this issue open because I think templates is a great idea. I do however want to see how I can utilize Laravel 5.3's new Email and Notification functionality to see if it would benefit templates in a LERN v4.0 release.

**Comment by sroutier** [comment]
That is great Tyler.
I will look at it ASAP.
Thanks a lot.
/S

**Comment by eleftrik** [comment]
Thank you @tylercd100, I will try ASAP

**Comment by eleftrik** [comment]
@tylercd100, I tried to use HTML, but I'm still receiving emails with expanded tags.
Can you please share an example?

**Comment by tylercd100** [comment]
@eleftrik @sroutier I got blade templates working with LERN

Check out the [README](https://github.com/tylercd100/lern#changing-the-body-of-the-notification) for the latest version. 
You will also need to run this line in the terminal if you want to use the default blade template
```
php artisan vendor:publish --provider="Tylercd100\LERN\LERNServiceProvider"
```

**Comment by tylercd100** [comment]
@eleftrik It looks like SMTP is not properly setting the email type to HTML for the email, I will get this fixed as soon as I can

**Comment by eleftrik** [comment]
> @eleftrik It looks like SMTP is not properly setting the email type to HTML for the email, I will get this fixed as soon as I can

Hi @tylercd100, was this fixed? I tried to upgrade to version 3.8.2, but I'm still receiving text only e-mails, with no line breaks and no HTML format.

Thank you

**Comment by eleftrik** [comment]
Now it works! Sorry, I forgot update my config file, adding `'view' => 'exceptions.default',`

One last issue: when I receive email, they always start with something like

`[2017-07-11 14:55:01] Tylercd100\LERN.CRITICAL:`

..and end with two empty arrays: `[] []`

In `resources/exceptions/default.blade.php` I'm not priting such arrays.

@tylercd100, have you any suggestion?

Thanks
